version: "3"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:admin@db:5432/myappdb?sslmode=disable
    networks:
      - mynetwork

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=mezinkdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8888:80"
    networks:
      - mynetwork

volumes:
  pgdata:

networks:
  mynetwork:
